export type StackDef = {
  id: string;
  name: string;
  language: string;
  icon: string;
  build?: string;
  start?: string;
  port?: number;
};

export const STACKS: StackDef[] = [
  { id: "auto", name: "Auto-detect", language: "Any", icon: "✨" },
  // JavaScript / TypeScript
  {
    id: "node",
    name: "Node.js",
    language: "JavaScript",
    icon: "⬢",
    build: "npm install && npm run build",
    start: "npm start",
    port: 3000,
  },
  {
    id: "next",
    name: "Next.js",
    language: "JavaScript",
    icon: "▲",
    build: "next build",
    start: "next start",
    port: 3000,
  },
  {
    id: "nuxt",
    name: "Nuxt",
    language: "JavaScript",
    icon: "💚",
    build: "nuxt build",
    start: "node .output/server/index.mjs",
    port: 3000,
  },
  {
    id: "remix",
    name: "Remix",
    language: "JavaScript",
    icon: "💿",
    build: "remix build",
    start: "remix-serve build",
    port: 3000,
  },
  {
    id: "astro",
    name: "Astro",
    language: "JavaScript",
    icon: "🚀",
    build: "astro build",
    start: "node ./dist/server/entry.mjs",
    port: 4321,
  },
  {
    id: "vite",
    name: "Vite / React",
    language: "JavaScript",
    icon: "⚡",
    build: "npm run build",
    start: "npm run preview",
    port: 4173,
  },
  {
    id: "sveltekit",
    name: "SvelteKit",
    language: "JavaScript",
    icon: "🔥",
    build: "vite build",
    start: "node build",
    port: 3000,
  },
  {
    id: "bun",
    name: "Bun",
    language: "JavaScript",
    icon: "🥟",
    build: "bun install",
    start: "bun run start",
    port: 3000,
  },
  {
    id: "deno",
    name: "Deno",
    language: "JavaScript",
    icon: "🦕",
    build: "deno cache main.ts",
    start: "deno run --allow-net main.ts",
    port: 8000,
  },
  {
    id: "tanstack",
    name: "TanStack Start",
    language: "JavaScript",
    icon: "🌀",
    build: "vite build",
    start: "node .output/server/index.mjs",
    port: 3000,
  },
  // Go
  {
    id: "go",
    name: "Go",
    language: "Go",
    icon: "🐹",
    build: "go build -o app .",
    start: "./app",
    port: 8080,
  },
  {
    id: "gin",
    name: "Go / Gin",
    language: "Go",
    icon: "🍸",
    build: "go build -o app .",
    start: "./app",
    port: 8080,
  },
  {
    id: "echo",
    name: "Go / Echo",
    language: "Go",
    icon: "🔊",
    build: "go build -o app .",
    start: "./app",
    port: 8080,
  },
  // Rust
  {
    id: "rust",
    name: "Rust / Axum",
    language: "Rust",
    icon: "🦀",
    build: "cargo build --release",
    start: "./target/release/app",
    port: 8080,
  },
  {
    id: "actix",
    name: "Rust / Actix",
    language: "Rust",
    icon: "🕸️",
    build: "cargo build --release",
    start: "./target/release/app",
    port: 8080,
  },
  {
    id: "rocket",
    name: "Rust / Rocket",
    language: "Rust",
    icon: "🚀",
    build: "cargo build --release",
    start: "./target/release/app",
    port: 8000,
  },
  // Python
  {
    id: "python",
    name: "Python / FastAPI",
    language: "Python",
    icon: "🐍",
    build: "pip install -r requirements.txt",
    start: "uvicorn main:app --host 0.0.0.0 --port $PORT",
    port: 8000,
  },
  {
    id: "django",
    name: "Django",
    language: "Python",
    icon: "🎸",
    build: "pip install -r requirements.txt",
    start: "gunicorn app.wsgi",
    port: 8000,
  },
  {
    id: "flask",
    name: "Flask",
    language: "Python",
    icon: "🧪",
    build: "pip install -r requirements.txt",
    start: "gunicorn app:app",
    port: 8000,
  },
  {
    id: "streamlit",
    name: "Streamlit",
    language: "Python",
    icon: "🎈",
    build: "pip install -r requirements.txt",
    start: "streamlit run app.py",
    port: 8501,
  },
  // Ruby
  {
    id: "ruby",
    name: "Ruby on Rails",
    language: "Ruby",
    icon: "💎",
    build: "bundle install",
    start: "bundle exec rails s",
    port: 3000,
  },
  {
    id: "sinatra",
    name: "Sinatra",
    language: "Ruby",
    icon: "🎩",
    build: "bundle install",
    start: "ruby app.rb",
    port: 4567,
  },
  // PHP
  {
    id: "laravel",
    name: "Laravel",
    language: "PHP",
    icon: "🐘",
    build: "composer install --no-dev",
    start: "php artisan serve --host=0.0.0.0 --port=$PORT",
    port: 8000,
  },
  {
    id: "symfony",
    name: "Symfony",
    language: "PHP",
    icon: "🎼",
    build: "composer install --no-dev",
    start: "symfony server:start",
    port: 8000,
  },
  {
    id: "wordpress",
    name: "WordPress",
    language: "PHP",
    icon: "📝",
    build: "composer install",
    start: "php -S 0.0.0.0:$PORT",
    port: 8080,
  },
  // Java / Kotlin
  {
    id: "spring",
    name: "Spring Boot",
    language: "Java",
    icon: "☕",
    build: "./mvnw package",
    start: "java -jar target/*.jar",
    port: 8080,
  },
  {
    id: "quarkus",
    name: "Quarkus",
    language: "Java",
    icon: "⚛️",
    build: "./mvnw package -Pnative",
    start: "./target/*-runner",
    port: 8080,
  },
  {
    id: "kotlin",
    name: "Kotlin / Ktor",
    language: "Kotlin",
    icon: "🟣",
    build: "./gradlew build",
    start: "java -jar build/libs/*.jar",
    port: 8080,
  },
  // C# / .NET
  {
    id: "dotnet",
    name: ".NET",
    language: "C#",
    icon: "🔷",
    build: "dotnet publish -c Release",
    start: "dotnet run",
    port: 5000,
  },
  {
    id: "aspnet",
    name: "ASP.NET Core",
    language: "C#",
    icon: "🌐",
    build: "dotnet publish -c Release",
    start: "dotnet ./out/app.dll",
    port: 5000,
  },
  // Elixir
  {
    id: "elixir",
    name: "Elixir / Phoenix",
    language: "Elixir",
    icon: "💧",
    build: "mix deps.get && mix compile",
    start: "mix phx.server",
    port: 4000,
  },
  {
    id: "elixir-nerves",
    name: "Elixir / Nerves",
    language: "Elixir",
    icon: "🪷",
    build: "mix deps.get",
    start: "mix run --no-halt",
    port: 4000,
  },
  // Docker
  {
    id: "docker",
    name: "Dockerfile",
    language: "Docker",
    icon: "🐳",
    build: "docker build -t app .",
    start: "docker run -p $PORT:$PORT app",
    port: 8080,
  },
  {
    id: "compose",
    name: "Docker Compose",
    language: "Docker",
    icon: "📚",
    build: "docker compose build",
    start: "docker compose up",
    port: 8080,
  },
  // Static
  {
    id: "static",
    name: "Static HTML",
    language: "HTML",
    icon: "📄",
    build: "npm run build",
    start: "serve dist",
    port: 8080,
  },
  {
    id: "hugo",
    name: "Hugo",
    language: "Static",
    icon: "📰",
    build: "hugo --minify",
    start: "hugo server",
    port: 1313,
  },
  {
    id: "jekyll",
    name: "Jekyll",
    language: "Static",
    icon: "🪶",
    build: "bundle exec jekyll build",
    start: "bundle exec jekyll serve",
    port: 4000,
  },
  {
    id: "eleventy",
    name: "Eleventy",
    language: "Static",
    icon: "1️⃣1️⃣",
    build: "eleventy",
    start: "eleventy --serve",
    port: 8080,
  },
  // Generic
  {
    id: "bash",
    name: "Bash script",
    language: "Generic",
    icon: "🐚",
    build: "chmod +x start.sh",
    start: "./start.sh",
    port: 3000,
  },
  {
    id: "custom",
    name: "Custom",
    language: "Generic",
    icon: "🔧",
    build: "make build",
    start: "make start",
    port: 3000,
  },
];

export const WORKSPACES = [
  { id: "none", name: "Single package", icon: "📦" },
  { id: "pnpm", name: "pnpm workspaces", icon: "🅿️" },
  { id: "npm", name: "npm/yarn workspaces", icon: "🅽" },
  { id: "yarn", name: "Yarn Berry", icon: "🧶" },
  { id: "rush", name: "Rush", icon: "🏃" },
  { id: "cargo", name: "Cargo workspace", icon: "🦀" },
  { id: "go", name: "Go workspace", icon: "🐹" },
  { id: "uv", name: "uv (Python)", icon: "🐍" },
  { id: "elixir", name: "Elixir umbrella", icon: "💧" },
  { id: "maven", name: "Maven multi-module", icon: "☕" },
  { id: "gradle", name: "Gradle multi-project", icon: "🐘" },
  { id: "dotnet", name: ".NET solution", icon: "🔷" },
] as const;

export const TARGETS = [
  {
    id: "docker",
    name: "Docker container",
    desc: "Isolated container on the local Docker daemon",
    icon: "🐳",
  },
  {
    id: "process",
    name: "Native process",
    desc: "Direct process managed by HosteraX supervisor",
    icon: "⚡",
  },
  { id: "ssh", name: "SSH Remote Host", desc: "Deploy over SSH to a remote server / VPS", icon: "🔐" },
] as const;

export const ENVIRONMENTS = [
  { id: "production", name: "Production", icon: "🟢" },
  { id: "preview", name: "Preview", icon: "🟡" },
  { id: "development", name: "Development", icon: "🔵" },
] as const;

export const REGIONS = [
  { id: "local", name: "Local (this machine / edge)", flag: "💻" },
  { id: "remote", name: "Remote Self-Hosted VPS", flag: "🖥️" },
];

// ==========================================
// 1. Framework & Starter Templates
// ==========================================
export type StarterTemplate = {
  id: string;
  name: string;
  category: "all" | "js_ts" | "python" | "go" | "rust" | "fullstack";
  desc: string;
  icon: string;
  repo_url: string;
  stack: string;
  port: number;
  tags: string[];
  popular?: boolean;
  env?: Record<string, string>;
};

export const STARTER_TEMPLATE_CATEGORIES = [
  { id: "all", label: "All Templates", icon: "🌟" },
  { id: "js_ts", label: "JavaScript / TypeScript", icon: "🟨" },
  { id: "python", label: "Python", icon: "🐍" },
  { id: "go", label: "Go", icon: "🐹" },
  { id: "rust", label: "Rust", icon: "🦀" },
  { id: "fullstack", label: "Full-Stack SSR", icon: "⚡" },
] as const;

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: "nextjs-starter",
    name: "Next.js 15 Starter",
    category: "js_ts",
    desc: "Production-ready Next.js 15 with App Router, TypeScript, and Tailwind CSS.",
    icon: "▲",
    repo_url: "https://github.com/vercel/next.js.git",
    stack: "next",
    port: 3000,
    tags: ["nextjs", "react", "typescript", "fullstack"],
    popular: true,
  },
  {
    id: "vite-react",
    name: "Vite + React SPA",
    category: "js_ts",
    desc: "Lightning fast React SPA with Vite, TypeScript, and hot module reload.",
    icon: "⚡",
    repo_url: "https://github.com/vitejs/vite.git",
    stack: "vite",
    port: 4173,
    tags: ["vite", "react", "spa", "frontend"],
    popular: true,
  },
  {
    id: "fastapi-starter",
    name: "FastAPI Python Microservice",
    category: "python",
    desc: "High-performance Python ASGI API framework with auto OpenAPI docs.",
    icon: "🐍",
    repo_url: "https://github.com/tiangolo/fastapi.git",
    stack: "python",
    port: 8000,
    tags: ["python", "fastapi", "api", "backend"],
    popular: true,
  },
  {
    id: "astro-starter",
    name: "Astro Content Web",
    category: "fullstack",
    desc: "Zero-JS by default content-driven static website and blog framework.",
    icon: "🚀",
    repo_url: "https://github.com/withastro/astro.git",
    stack: "astro",
    port: 4321,
    tags: ["astro", "ssg", "content", "markdown"],
  },
  {
    id: "go-gin",
    name: "Go / Gin REST API",
    category: "go",
    desc: "Martini-like API with blazing fast performance & low memory footprint.",
    icon: "🍸",
    repo_url: "https://github.com/gin-gonic/gin.git",
    stack: "gin",
    port: 8080,
    tags: ["go", "gin", "backend", "microservice"],
  },
  {
    id: "rust-axum",
    name: "Rust / Axum Web Service",
    category: "rust",
    desc: "Ergonomic and modular web framework built with Tokio and Tower.",
    icon: "🦀",
    repo_url: "https://github.com/tokio-rs/axum.git",
    stack: "rust",
    port: 8080,
    tags: ["rust", "axum", "async", "high-performance"],
  },
  {
    id: "nuxt-starter",
    name: "Nuxt 3 Vue Fullstack",
    category: "fullstack",
    desc: "Intuitive Vue 3 full-stack framework with SSR, nitro engine, and routing.",
    icon: "💚",
    repo_url: "https://github.com/nuxt/starter.git",
    stack: "nuxt",
    port: 3000,
    tags: ["vue", "nuxt", "fullstack", "ssr"],
  },
  {
    id: "remix-starter",
    name: "Remix Fullstack Web",
    category: "fullstack",
    desc: "Focused on web standards and modern UX with fast server-rendered routes.",
    icon: "💿",
    repo_url: "https://github.com/remix-run/remix.git",
    stack: "remix",
    port: 3000,
    tags: ["remix", "react", "fullstack"],
  },
  {
    id: "sveltekit-starter",
    name: "SvelteKit App",
    category: "js_ts",
    desc: "Cybernetically enhanced web apps with ultra-compact bundle sizes.",
    icon: "🔥",
    repo_url: "https://github.com/sveltejs/kit.git",
    stack: "sveltekit",
    port: 3000,
    tags: ["svelte", "sveltekit", "frontend"],
  },
];

// ==========================================
// 2. One-Click Self-Hosted Docker Apps
// ==========================================
export type OneClickAppCategory =
  | "all"
  | "ai_automation"
  | "devtools"
  | "cms_media"
  | "database"
  | "security_analytics"
  | "media_cloud"
  | "productivity_tools"
  | "networking_vpn";

export type OneClickAppSource = "all" | "verified" | "awesome_selfhosted" | "awesome_sysadmin" | "selfhst";

export type OneClickAppDef = {
  id: string;
  slug: string;
  name: string;
  category: OneClickAppCategory | string;
  categoryLabel?: string;
  desc: string;
  icon?: string;
  image: string;
  port: number;
  tags: string[];
  popular?: boolean;
  source?: "verified" | "awesome_selfhosted" | "awesome_sysadmin" | "selfhst" | string;
  sources?: string[];
  website?: string;
  url?: string;
  stars?: string;
  forks?: string;
  language?: string;
  license?: string;
  updatedAt?: string;
  logoUrl?: string | null;
  svgUrl?: string | null;
  webpIcon?: string | null;
  logoType?: string;
  env?: Record<string, string>;
};

export const ONE_CLICK_APP_CATEGORIES = [
  { id: "all", label: "All Apps", icon: "🌟" },
  { id: "ai_automation", label: "AI & LLMs", icon: "🤖" },
  { id: "devtools", label: "DevTools & Homelab", icon: "🛠️" },
  { id: "cms_media", label: "CMS & Low-Code", icon: "📦" },
  { id: "database", label: "Databases & Vectors", icon: "🗄️" },
  { id: "security_analytics", label: "Security & Analytics", icon: "🔒" },
  { id: "media_cloud", label: "Media & Streaming", icon: "🎬" },
  { id: "productivity_tools", label: "Productivity & Notes", icon: "📝" },
  { id: "networking_vpn", label: "Networking & VPN", icon: "🌐" },
] as const;

export const ONE_CLICK_SOURCES = [
  { id: "all", label: "✨ All (2,550+ Apps)", icon: "✨" },
  { id: "verified", label: "🌟 Verified 1-Click", icon: "🛡️" },
  { id: "awesome_selfhosted", label: "⚡ Awesome-Selfhosted", icon: "📚" },
  { id: "awesome_sysadmin", label: "🛠️ SysAdmin / DevOps", icon: "⚙️" },
  { id: "selfhst", label: "🌐 selfh.st (1,330+)", icon: "🚀" },
] as const;

export const ONE_CLICK_APPS_CATALOG: OneClickAppDef[] = [
  // ==========================================
  // 1. AI & LLM Automation
  // ==========================================
  {
    id: "n8n",
    slug: "n8n",
    name: "n8n",
    category: "ai_automation",
    desc: "Fair-code workflow automation with autonomous AI agent nodes & 400+ integrations.",
    icon: "🔗",
    image: "docker.n8n.io/n8nio/n8n",
    port: 5678,
    tags: ["automation", "workflow", "ai", "docker"],
    popular: true,
    source: "verified",
    website: "https://n8n.io",
    stars: "50k+",
    env: {
      N8N_SECURE_COOKIE: "false",
      N8N_HOST: "0.0.0.0",
      GENERIC_TIMEZONE: "UTC",
    },
  },
  {
    id: "open-webui",
    slug: "open-webui",
    name: "Open-WebUI",
    category: "ai_automation",
    desc: "Feature-rich, self-hosted web UI for LLMs, Ollama, OpenAI, RAG, and multimodal agents.",
    icon: "💬",
    image: "ghcr.io/open-webui/open-webui:main",
    port: 8080,
    tags: ["ai", "chatgpt", "ollama", "ui", "rag"],
    popular: true,
    source: "verified",
    website: "https://openwebui.com",
    stars: "65k+",
    env: {
      WEBUI_AUTH: "false",
    },
  },
  {
    id: "ollama",
    slug: "ollama",
    name: "Ollama",
    category: "ai_automation",
    desc: "Get up and running with Llama 3, DeepSeek-R1, Mistral, and local LLMs in seconds.",
    icon: "🦙",
    image: "ollama/ollama:latest",
    port: 11434,
    tags: ["ai", "local-llm", "llama", "deepseek"],
    popular: true,
    source: "verified",
    website: "https://ollama.com",
    stars: "110k+",
    env: {
      OLLAMA_HOST: "0.0.0.0",
    },
  },
  {
    id: "flowise",
    slug: "flowise",
    name: "Flowise",
    category: "ai_automation",
    desc: "Drag & drop visual builder for customized LangChain LLM flows and multi-agent systems.",
    icon: "🧠",
    image: "flowiseai/flowise:latest",
    port: 3000,
    tags: ["ai", "langchain", "llm", "agents"],
    popular: true,
    source: "verified",
    website: "https://flowiseai.com",
    stars: "35k+",
  },
  {
    id: "anything-llm",
    slug: "anything-llm",
    name: "AnythingLLM",
    category: "ai_automation",
    desc: "All-in-one desktop & server AI assistant with built-in vector store, RAG, and document parsing.",
    icon: "🔮",
    image: "mintplexlabs/anything-llm:latest",
    port: 3001,
    tags: ["ai", "rag", "documents", "vector"],
    popular: true,
    source: "selfhst",
    website: "https://anythingllm.com",
    stars: "30k+",
  },
  {
    id: "langfuse",
    slug: "langfuse",
    name: "Langfuse",
    category: "ai_automation",
    desc: "Open source LLM engineering platform: observability, prompt management, and evals.",
    icon: "⚡",
    image: "langfuse/langfuse:2",
    port: 3000,
    tags: ["ai", "observability", "prompts", "evals"],
    source: "awesome_selfhosted",
    website: "https://langfuse.com",
    stars: "8k+",
  },
  {
    id: "dify",
    slug: "dify",
    name: "Dify.AI",
    category: "ai_automation",
    desc: "Easy-to-use LLMOps platform for creating assistant apps, AI workflows, and multi-agent systems.",
    icon: "🤖",
    image: "langgenius/dify-api:latest",
    port: 5001,
    tags: ["ai", "llmops", "agents", "rag"],
    popular: true,
    source: "selfhst",
    website: "https://dify.ai",
    stars: "55k+",
  },

  // ==========================================
  // 2. DevTools & Homelab
  // ==========================================
  {
    id: "gitea",
    slug: "gitea",
    name: "Gitea",
    category: "devtools",
    desc: "Lightweight, painless self-hosted Git platform with pull requests, issues, and CI runner support.",
    icon: "🍵",
    image: "gitea/gitea:latest",
    port: 3000,
    tags: ["git", "devtools", "vcs", "docker"],
    popular: true,
    source: "verified",
    website: "https://gitea.io",
    stars: "45k+",
  },
  {
    id: "forgejo",
    slug: "forgejo",
    name: "Forgejo",
    category: "devtools",
    desc: "Community-driven, 100% free software code hosting and Git collaboration platform.",
    icon: "🔨",
    image: "codeberg.org/forgejo/forgejo:latest",
    port: 3000,
    tags: ["git", "forgejo", "codeberg", "foss"],
    source: "awesome_selfhosted",
    website: "https://forgejo.org",
  },
  {
    id: "code-server",
    slug: "code-server",
    name: "code-server (VS Code)",
    category: "devtools",
    desc: "Full Visual Studio Code running directly in the browser on your host machine.",
    icon: "💻",
    image: "codercom/code-server:latest",
    port: 8080,
    tags: ["ide", "vscode", "devtools", "editor"],
    popular: true,
    source: "verified",
    website: "https://coder.com",
    stars: "68k+",
    env: {
      AUTH: "none",
    },
  },
  {
    id: "uptime-kuma",
    slug: "uptime-kuma",
    name: "Uptime Kuma",
    category: "devtools",
    desc: "Self-hosted monitoring tool with real-time ping charts, status pages, and instant alerts.",
    icon: "📶",
    image: "louislam/uptime-kuma:1",
    port: 3001,
    tags: ["monitoring", "status", "uptime", "docker"],
    popular: true,
    source: "verified",
    website: "https://uptime.kuma.pet",
    stars: "60k+",
  },
  {
    id: "dockge",
    slug: "dockge",
    name: "Dockge",
    category: "devtools",
    desc: "Easy-to-use, fancy, reactive Docker Compose stack manager by the creator of Uptime Kuma.",
    icon: "🐳",
    image: "louislam/dockge:1",
    port: 5001,
    tags: ["docker", "compose", "manager", "homelab"],
    popular: true,
    source: "selfhst",
    website: "https://dockge.kuma.pet",
    stars: "18k+",
  },
  {
    id: "stirling-pdf",
    slug: "stirling-pdf",
    name: "Stirling PDF",
    category: "devtools",
    desc: "Robust, locally hosted one-stop-shop web application for all PDF split, merge, OCR, and convert tasks.",
    icon: "📄",
    image: "frooodle/s-pdf:latest",
    port: 8080,
    tags: ["pdf", "tools", "ocr", "converter"],
    popular: true,
    source: "verified",
    website: "https://stirlingpdf.com",
    stars: "48k+",
  },
  {
    id: "homepage",
    slug: "homepage",
    name: "Homepage Dashboard",
    category: "devtools",
    desc: "Highly customizable, ultra-fast application dashboard and homelab landing portal.",
    icon: "🏠",
    image: "ghcr.io/gethomepage/homepage:latest",
    port: 3000,
    tags: ["dashboard", "homelab", "startpage"],
    source: "selfhst",
    website: "https://gethomepage.dev",
    stars: "22k+",
  },
  {
    id: "it-tools",
    slug: "it-tools",
    name: "IT-Tools",
    category: "devtools",
    desc: "Handy collection of 80+ online tools for developers and IT professionals (JWT, Hash, Regex, Base64).",
    icon: "🧰",
    image: "corentinth/it-tools:latest",
    port: 80,
    tags: ["devtools", "utilities", "converter", "jwt"],
    popular: true,
    source: "awesome_selfhosted",
    website: "https://it-tools.tech",
    stars: "25k+",
  },
  {
    id: "cyberchef",
    slug: "cyberchef",
    name: "CyberChef",
    category: "devtools",
    desc: "The Cyber Swiss Army Knife - a web app for encryption, encoding, compression, and data analysis.",
    icon: "🧁",
    image: "mpepping/cyberchef:latest",
    port: 8000,
    tags: ["security", "crypto", "decoder", "analysis"],
    source: "awesome_selfhosted",
    website: "https://gchq.github.io/CyberChef",
    stars: "28k+",
  },
  {
    id: "excalidraw",
    slug: "excalidraw",
    name: "Excalidraw",
    category: "devtools",
    desc: "Virtual collaborative whiteboard for sketching hand-drawn like architecture diagrams.",
    icon: "🎨",
    image: "excalidraw/excalidraw:latest",
    port: 80,
    tags: ["whiteboard", "diagrams", "collaboration"],
    source: "awesome_selfhosted",
    website: "https://excalidraw.com",
    stars: "85k+",
  },

  // ==========================================
  // 3. CMS & Low-Code Backends
  // ==========================================
  {
    id: "ghost",
    slug: "ghost",
    name: "Ghost",
    category: "cms_media",
    desc: "Independent technology for modern publishing, blogs, membership sites, and newsletters.",
    icon: "👻",
    image: "ghost:5",
    port: 2368,
    tags: ["cms", "blog", "publishing", "newsletter"],
    popular: true,
    source: "verified",
    website: "https://ghost.org",
    stars: "48k+",
  },
  {
    id: "nocodb",
    slug: "nocodb",
    name: "NocoDB",
    category: "cms_media",
    desc: "Open source Airtable alternative that turns any SQL database into a smart spreadsheet.",
    icon: "📊",
    image: "nocodb/nocodb:latest",
    port: 8080,
    tags: ["airtable", "spreadsheet", "nocode", "database"],
    popular: true,
    source: "verified",
    website: "https://nocodb.com",
    stars: "45k+",
  },
  {
    id: "pocketbase",
    slug: "pocketbase",
    name: "PocketBase",
    category: "cms_media",
    desc: "Open Source backend in 1 binary with realtime subscriptions, auth, and embedded SQLite.",
    icon: "👝",
    image: "ghcr.io/muchobien/pocketbase:latest",
    port: 8090,
    tags: ["backend", "baas", "realtime", "sqlite"],
    popular: true,
    source: "verified",
    website: "https://pocketbase.io",
    stars: "40k+",
  },
  {
    id: "directus",
    slug: "directus",
    name: "Directus",
    category: "cms_media",
    desc: "Instant real-time GraphQL and REST API layers over your database with intuitive admin app.",
    icon: "📦",
    image: "directus/directus:latest",
    port: 8055,
    tags: ["cms", "headless", "api", "database"],
    source: "awesome_selfhosted",
    website: "https://directus.io",
    stars: "28k+",
  },
  {
    id: "strapi",
    slug: "strapi",
    name: "Strapi CMS",
    category: "cms_media",
    desc: "Leading open-source headless CMS that is 100% JavaScript / TypeScript and fully customizable.",
    icon: "✨",
    image: "strapi/strapi:latest",
    port: 1337,
    tags: ["cms", "node", "api", "headless"],
    source: "awesome_selfhosted",
    website: "https://strapi.io",
    stars: "64k+",
  },
  {
    id: "docmost",
    slug: "docmost",
    name: "Docmost",
    category: "cms_media",
    desc: "Open-source collaborative knowledge base and Notion alternative with real-time editing.",
    icon: "📚",
    image: "docmost/docmost:latest",
    port: 3000,
    tags: ["wiki", "notion", "docs", "knowledge"],
    popular: true,
    source: "selfhst",
    website: "https://docmost.com",
    stars: "9k+",
  },
  {
    id: "appwrite",
    slug: "appwrite",
    name: "Appwrite",
    category: "cms_media",
    desc: "Self-hosted backend server for web, mobile, and flutter developers with auth, db, & storage.",
    icon: "🚀",
    image: "appwrite/appwrite:latest",
    port: 80,
    tags: ["baas", "auth", "database", "storage"],
    source: "awesome_selfhosted",
    website: "https://appwrite.io",
    stars: "45k+",
  },
  {
    id: "wordpress",
    slug: "wordpress",
    name: "WordPress",
    category: "cms_media",
    desc: "The world's most popular open source web publishing platform and content management system.",
    icon: "🌐",
    image: "wordpress:latest",
    port: 80,
    tags: ["cms", "blog", "website", "php"],
    source: "awesome_selfhosted",
    website: "https://wordpress.org",
  },

  // ==========================================
  // 4. Databases & Vector Search
  // ==========================================
  {
    id: "redis-commander",
    slug: "redis-commander",
    name: "Redis Commander",
    category: "database",
    desc: "Web management user interface for Redis in-memory cache and key-value datastores.",
    icon: "🔴",
    image: "rediscommander/redis-commander:latest",
    port: 8081,
    tags: ["redis", "database", "cache", "ui"],
    source: "awesome_selfhosted",
  },
  {
    id: "pgadmin",
    slug: "pgadmin",
    name: "pgAdmin 4",
    category: "database",
    desc: "Comprehensive PostgreSQL administration, query tool, and schema management platform.",
    icon: "🐘",
    image: "dpage/pgadmin4:latest",
    port: 5050,
    tags: ["postgres", "database", "sql", "admin"],
    source: "verified",
    env: {
      PGADMIN_DEFAULT_EMAIL: "admin@hosterax.local",
      PGADMIN_DEFAULT_PASSWORD: "admin",
    },
  },
  {
    id: "meilisearch",
    slug: "meilisearch",
    name: "Meilisearch",
    category: "database",
    desc: "Lightning-fast, highly relevant, and typo-tolerant search engine API designed for developers.",
    icon: "🔍",
    image: "getmeili/meilisearch:latest",
    port: 7700,
    tags: ["search", "indexing", "fast", "engine"],
    source: "verified",
    env: {
      MEILI_NO_ANALYTICS: "true",
      MEILI_ENV: "production",
    },
  },
  {
    id: "typesense",
    slug: "typesense",
    name: "Typesense",
    category: "database",
    desc: "Fast, typo-tolerant, in-memory open-source search engine alternative to Algolia.",
    icon: "⚡",
    image: "typesense/typesense:27.1",
    port: 8108,
    tags: ["search", "algolia", "fast", "vector"],
    source: "awesome_selfhosted",
    website: "https://typesense.org",
  },
  {
    id: "qdrant",
    slug: "qdrant",
    name: "Qdrant Vector DB",
    category: "database",
    desc: "Vector similarity search engine and vector database with extended filtering support for AI.",
    icon: "🎯",
    image: "qdrant/qdrant:latest",
    port: 6333,
    tags: ["vector", "embeddings", "ai", "search"],
    popular: true,
    source: "verified",
    website: "https://qdrant.tech",
    stars: "22k+",
  },
  {
    id: "chroma",
    slug: "chroma",
    name: "Chroma DB",
    category: "database",
    desc: "AI-native open-source embedding database for building LLM applications with memory.",
    icon: "🎨",
    image: "chromadb/chroma:latest",
    port: 8000,
    tags: ["embeddings", "vector", "ai", "rag"],
    source: "awesome_selfhosted",
    website: "https://trychroma.com",
    stars: "16k+",
  },
  {
    id: "minio",
    slug: "minio",
    name: "MinIO S3 Object Storage",
    category: "database",
    desc: "High-performance S3-compatible object storage server for modern data infrastructure.",
    icon: "🪣",
    image: "minio/minio:latest",
    port: 9000,
    tags: ["s3", "storage", "blobs", "minio"],
    source: "awesome_selfhosted",
    website: "https://min.io",
    stars: "46k+",
  },

  // ==========================================
  // 5. Security & Analytics
  // ==========================================
  {
    id: "vaultwarden",
    slug: "vaultwarden",
    name: "Vaultwarden",
    category: "security_analytics",
    desc: "Lightweight, unofficial Bitwarden password manager server written in Rust with full browser sync.",
    icon: "🔒",
    image: "vaultwarden/server:latest",
    port: 80,
    tags: ["security", "password-manager", "vault", "rust"],
    popular: true,
    source: "verified",
    website: "https://github.com/dani-garcia/vaultwarden",
    stars: "40k+",
    env: {
      WEBSOCKET_ENABLED: "true",
      SIGNUPS_ALLOWED: "true",
    },
  },
  {
    id: "metabase",
    slug: "metabase",
    name: "Metabase",
    category: "security_analytics",
    desc: "Self-service business intelligence, SQL querying, and live KPI dashboards for your company.",
    icon: "📊",
    image: "metabase/metabase:latest",
    port: 3000,
    tags: ["bi", "analytics", "sql", "visualization"],
    popular: true,
    source: "verified",
    website: "https://metabase.com",
    stars: "38k+",
  },
  {
    id: "umami",
    slug: "umami",
    name: "Umami Analytics",
    category: "security_analytics",
    desc: "Simple, fast, privacy-focused, cookie-free Google Analytics alternative with gorgeous graphs.",
    icon: "📈",
    image: "ghcr.io/umami-software/umami:postgresql-latest",
    port: 3000,
    tags: ["analytics", "privacy", "cookieless", "stats"],
    popular: true,
    source: "verified",
    website: "https://umami.is",
    stars: "24k+",
  },
  {
    id: "plausible",
    slug: "plausible",
    name: "Plausible Analytics",
    category: "security_analytics",
    desc: "Lightweight, open-source web analytics without cookies and fully compliant with GDPR.",
    icon: "📉",
    image: "plausible/analytics:latest",
    port: 8000,
    tags: ["analytics", "privacy", "gdpr", "dashboard"],
    source: "awesome_selfhosted",
    website: "https://plausible.io",
    stars: "19k+",
  },
  {
    id: "grafana",
    slug: "grafana",
    name: "Grafana",
    category: "security_analytics",
    desc: "The open observability platform for visualizing metrics, logs, and traces from any source.",
    icon: "📈",
    image: "grafana/grafana:latest",
    port: 3000,
    tags: ["monitoring", "metrics", "dashboards", "prometheus"],
    popular: true,
    source: "verified",
    website: "https://grafana.com",
    stars: "63k+",
    env: {
      GF_SECURITY_ALLOW_EMBEDDING: "true",
    },
  },

  // ==========================================
  // 6. Media & Streaming
  // ==========================================
  {
    id: "immich",
    slug: "immich",
    name: "Immich Photos",
    category: "media_cloud",
    desc: "High-performance self-hosted photo and video backup solution with facial recognition & mobile apps.",
    icon: "📸",
    image: "ghcr.io/immich-app/immich-server:release",
    port: 2283,
    tags: ["photos", "backup", "google-photos", "media"],
    popular: true,
    source: "verified",
    website: "https://immich.app",
    stars: "55k+",
  },
  {
    id: "jellyfin",
    slug: "jellyfin",
    name: "Jellyfin",
    category: "media_cloud",
    desc: "The Free Software Media System that puts you in control of managing and streaming your media.",
    icon: "🍿",
    image: "jellyfin/jellyfin:latest",
    port: 8096,
    tags: ["media", "streaming", "movies", "plex"],
    popular: true,
    source: "verified",
    website: "https://jellyfin.org",
    stars: "34k+",
  },
  {
    id: "navidrome",
    slug: "navidrome",
    name: "Navidrome",
    category: "media_cloud",
    desc: "Modern open-source music server and streamer with Subsonic API and Spotify-like UI.",
    icon: "🎵",
    image: "deluan/navidrome:latest",
    port: 4533,
    tags: ["music", "audio", "streaming", "subsonic"],
    popular: true,
    source: "selfhst",
    website: "https://navidrome.org",
    stars: "14k+",
  },
  {
    id: "audiobookshelf",
    slug: "audiobookshelf",
    name: "Audiobookshelf",
    category: "media_cloud",
    desc: "Self-hosted audiobook and podcast server with multi-user sync and dedicated companion apps.",
    icon: "🎧",
    image: "ghcr.io/advplyr/audiobookshelf:latest",
    port: 80,
    tags: ["audiobooks", "podcasts", "streaming", "media"],
    popular: true,
    source: "selfhst",
    website: "https://audiobookshelf.org",
    stars: "16k+",
  },
  {
    id: "kavita",
    slug: "kavita",
    name: "Kavita",
    category: "media_cloud",
    desc: "Fast, feature-rich self-hosted digital library designed for reading manga, comics, and eBooks.",
    icon: "📖",
    image: "jvmilazz0/kavita:latest",
    port: 5000,
    tags: ["books", "manga", "comics", "reader"],
    source: "selfhst",
    website: "https://kavitareader.com",
    stars: "6k+",
  },

  // ==========================================
  // 7. Productivity & Notes
  // ==========================================
  {
    id: "paperless-ngx",
    slug: "paperless-ngx",
    name: "Paperless-ngx",
    category: "productivity_tools",
    desc: "Supercharged document management system that indexes, OCRs, and organizes your physical scans.",
    icon: "📑",
    image: "ghcr.io/paperless-ngx/paperless-ngx:latest",
    port: 8000,
    tags: ["documents", "ocr", "scanner", "pdf"],
    popular: true,
    source: "selfhst",
    website: "https://paperless-ngx.readthedocs.io",
    stars: "24k+",
  },
  {
    id: "memos",
    slug: "memos",
    name: "Memos",
    category: "productivity_tools",
    desc: "Privacy-first, lightweight note-taking service. Easily capture and share your thoughts.",
    icon: "📝",
    image: "neosmemo/memos:latest",
    port: 5230,
    tags: ["notes", "twitter", "markdown", "privacy"],
    popular: true,
    source: "awesome_selfhosted",
    website: "https://usememos.com",
    stars: "34k+",
  },
  {
    id: "vikunja",
    slug: "vikunja",
    name: "Vikunja",
    category: "productivity_tools",
    desc: "The open-source, self-hostable to-do app with Gantt charts, Kanban boards, and checklists.",
    icon: "✅",
    image: "vikunja/vikunja:latest",
    port: 3456,
    tags: ["todo", "tasks", "gantt", "kanban"],
    popular: true,
    source: "awesome_selfhosted",
    website: "https://vikunja.io",
    stars: "12k+",
  },
  {
    id: "mealie",
    slug: "mealie",
    name: "Mealie",
    category: "productivity_tools",
    desc: "Self-hosted recipe manager and meal planner with automatic web scraping and shopping lists.",
    icon: "🍳",
    image: "ghcr.io/mealie-recipes/mealie:latest",
    port: 9000,
    tags: ["recipes", "cooking", "planner", "food"],
    source: "selfhst",
    website: "https://mealie.io",
    stars: "8k+",
  },
  {
    id: "linkwarden",
    slug: "linkwarden",
    name: "Linkwarden",
    category: "productivity_tools",
    desc: "Self-hosted collaborative bookmark manager to collect, organize, and archive web pages.",
    icon: "🔖",
    image: "ghcr.io/linkwarden/linkwarden:latest",
    port: 3000,
    tags: ["bookmarks", "archive", "reading", "web"],
    popular: true,
    source: "awesome_selfhosted",
    website: "https://linkwarden.app",
    stars: "9k+",
  },
  {
    id: "nextcloud",
    slug: "nextcloud",
    name: "Nextcloud Hub",
    category: "productivity_tools",
    desc: "Self-hosted productivity platform providing file sync, sharing, office documents, and calendar.",
    icon: "☁️",
    image: "nextcloud:latest",
    port: 80,
    tags: ["cloud", "storage", "files", "collaboration"],
    popular: true,
    source: "verified",
    website: "https://nextcloud.com",
  },

  // ==========================================
  // 8. Networking & VPN
  // ==========================================
  {
    id: "wg-easy",
    slug: "wg-easy",
    name: "WG-Easy (WireGuard)",
    category: "networking_vpn",
    desc: "The easiest way to run and manage WireGuard VPN with a built-in web administration UI & QR codes.",
    icon: "🛡️",
    image: "ghcr.io/wg-easy/wg-easy:latest",
    port: 51821,
    tags: ["vpn", "wireguard", "networking", "security"],
    popular: true,
    source: "selfhst",
    website: "https://github.com/wg-easy/wg-easy",
    stars: "17k+",
  },
  {
    id: "searxng",
    slug: "searxng",
    name: "SearXNG",
    category: "networking_vpn",
    desc: "Privacy-respecting, open metasearch engine aggregating results from 70+ search engines.",
    icon: "🔎",
    image: "searxng/searxng:latest",
    port: 8080,
    tags: ["search", "privacy", "metasearch", "google"],
    popular: true,
    source: "awesome_selfhosted",
    website: "https://searx.space",
    stars: "14k+",
  },
  {
    id: "rustdesk",
    slug: "rustdesk",
    name: "RustDesk Server",
    category: "networking_vpn",
    desc: "Open source remote desktop alternative to TeamViewer and AnyDesk with self-hosted relay.",
    icon: "🖥️",
    image: "rustdesk/rustdesk-server:latest",
    port: 21117,
    tags: ["remote-desktop", "teamviewer", "relay", "rust"],
    popular: true,
    source: "awesome_selfhosted",
    website: "https://rustdesk.com",
    stars: "75k+",
  },
  {
    id: "shlink",
    slug: "shlink",
    name: "Shlink",
    category: "networking_vpn",
    desc: "Self-hosted URL shortener with REST API, rich visit analytics, and custom domain routing.",
    icon: "🔗",
    image: "shlinkio/shlink:latest",
    port: 8080,
    tags: ["url-shortener", "bitly", "analytics", "links"],
    source: "selfhst",
    website: "https://shlink.io",
    stars: "4k+",
  },
];

// Backwards compatibility aliases
export const ONE_CLICK_APPS = ONE_CLICK_APPS_CATALOG;
export const APP_TEMPLATES = STARTER_TEMPLATES;
export const UNIFIED_TEMPLATES_AND_APPS = [...STARTER_TEMPLATES, ...ONE_CLICK_APPS_CATALOG];


