/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppAppsRouteImport } from './routes/_app.apps'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDatabasesRouteImport } from './routes/_app.databases'
import { Route as AppDeploymentsRouteImport } from './routes/_app.deployments'
import { Route as AppDockerhubRouteImport } from './routes/_app.dockerhub'
import { Route as AppDomainsRouteImport } from './routes/_app.domains'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppLocalRouteImport } from './routes/_app.local'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppOauthRouteImport } from './routes/_app.oauth'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTokensRouteImport } from './routes/_app.tokens'
import { Route as AppPSlugRouteImport } from './routes/_app.p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabasesRoute = AppDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsRoute = AppDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppRoute,
} as any)
const AppDockerhubRoute = AppDockerhubRouteImport.update({
  id: '/dockerhub',
  path: '/dockerhub',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppLocalRoute = AppLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOauthRoute = AppOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTokensRoute = AppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugRoute = AppPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/apps': typeof AppAppsRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/deployments': typeof AppDeploymentsRoute
  '/dockerhub': typeof AppDockerhubRoute
  '/domains': typeof AppDomainsRoute
  '/jobs': typeof AppJobsRoute
  '/local': typeof AppLocalRoute
  '/new': typeof AppNewRoute
  '/oauth': typeof AppOauthRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/p/$slug': typeof AppPSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/apps': typeof AppAppsRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/deployments': typeof AppDeploymentsRoute
  '/dockerhub': typeof AppDockerhubRoute
  '/domains': typeof AppDomainsRoute
  '/jobs': typeof AppJobsRoute
  '/local': typeof AppLocalRoute
  '/new': typeof AppNewRoute
  '/oauth': typeof AppOauthRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/p/$slug': typeof AppPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/apps': typeof AppAppsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/databases': typeof AppDatabasesRoute
  '/_app/deployments': typeof AppDeploymentsRoute
  '/_app/dockerhub': typeof AppDockerhubRoute
  '/_app/domains': typeof AppDomainsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/local': typeof AppLocalRoute
  '/_app/new': typeof AppNewRoute
  '/_app/oauth': typeof AppOauthRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tokens': typeof AppTokensRoute
  '/_app/p/$slug': typeof AppPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/apps'
    | '/dashboard'
    | '/databases'
    | '/deployments'
    | '/dockerhub'
    | '/domains'
    | '/jobs'
    | '/local'
    | '/new'
    | '/oauth'
    | '/servers'
    | '/settings'
    | '/tokens'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/apps'
    | '/dashboard'
    | '/databases'
    | '/deployments'
    | '/dockerhub'
    | '/domains'
    | '/jobs'
    | '/local'
    | '/new'
    | '/oauth'
    | '/servers'
    | '/settings'
    | '/tokens'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/activity'
    | '/_app/apps'
    | '/_app/dashboard'
    | '/_app/databases'
    | '/_app/deployments'
    | '/_app/dockerhub'
    | '/_app/domains'
    | '/_app/jobs'
    | '/_app/local'
    | '/_app/new'
    | '/_app/oauth'
    | '/_app/servers'
    | '/_app/settings'
    | '/_app/tokens'
    | '/_app/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps': {
      id: '/_app/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/databases': {
      id: '/_app/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AppDatabasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments': {
      id: '/_app/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AppDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dockerhub': {
      id: '/_app/dockerhub'
      path: '/dockerhub'
      fullPath: '/dockerhub'
      preLoaderRoute: typeof AppDockerhubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/local': {
      id: '/_app/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof AppLocalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oauth': {
      id: '/_app/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof AppOauthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tokens': {
      id: '/_app/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AppTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug': {
      id: '/_app/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof AppPSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAppsRoute: typeof AppAppsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabasesRoute: typeof AppDatabasesRoute
  AppDeploymentsRoute: typeof AppDeploymentsRoute
  AppDockerhubRoute: typeof AppDockerhubRoute
  AppDomainsRoute: typeof AppDomainsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLocalRoute: typeof AppLocalRoute
  AppNewRoute: typeof AppNewRoute
  AppOauthRoute: typeof AppOauthRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTokensRoute: typeof AppTokensRoute
  AppPSlugRoute: typeof AppPSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAppsRoute: AppAppsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabasesRoute: AppDatabasesRoute,
  AppDeploymentsRoute: AppDeploymentsRoute,
  AppDockerhubRoute: AppDockerhubRoute,
  AppDomainsRoute: AppDomainsRoute,
  AppJobsRoute: AppJobsRoute,
  AppLocalRoute: AppLocalRoute,
  AppNewRoute: AppNewRoute,
  AppOauthRoute: AppOauthRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTokensRoute: AppTokensRoute,
  AppPSlugRoute: AppPSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
