/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTokensRouteImport } from './routes/_app.tokens'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOauthRouteImport } from './routes/_app.oauth'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppLocalRouteImport } from './routes/_app.local'
import { Route as AppDeploymentsRouteImport } from './routes/_app.deployments'
import { Route as AppDatabasesRouteImport } from './routes/_app.databases'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppPSlugRouteImport } from './routes/_app.p.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTokensRoute = AppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOauthRoute = AppOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLocalRoute = AppLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsRoute = AppDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabasesRoute = AppDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugRoute = AppPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/deployments': typeof AppDeploymentsRoute
  '/local': typeof AppLocalRoute
  '/new': typeof AppNewRoute
  '/oauth': typeof AppOauthRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/p/$slug': typeof AppPSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/deployments': typeof AppDeploymentsRoute
  '/local': typeof AppLocalRoute
  '/new': typeof AppNewRoute
  '/oauth': typeof AppOauthRoute
  '/settings': typeof AppSettingsRoute
  '/tokens': typeof AppTokensRoute
  '/p/$slug': typeof AppPSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/databases': typeof AppDatabasesRoute
  '/_app/deployments': typeof AppDeploymentsRoute
  '/_app/local': typeof AppLocalRoute
  '/_app/new': typeof AppNewRoute
  '/_app/oauth': typeof AppOauthRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tokens': typeof AppTokensRoute
  '/_app/p/$slug': typeof AppPSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/databases'
    | '/deployments'
    | '/local'
    | '/new'
    | '/oauth'
    | '/settings'
    | '/tokens'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/databases'
    | '/deployments'
    | '/local'
    | '/new'
    | '/oauth'
    | '/settings'
    | '/tokens'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/databases'
    | '/_app/deployments'
    | '/_app/local'
    | '/_app/new'
    | '/_app/oauth'
    | '/_app/settings'
    | '/_app/tokens'
    | '/_app/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tokens': {
      id: '/_app/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AppTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oauth': {
      id: '/_app/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof AppOauthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/local': {
      id: '/_app/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof AppLocalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments': {
      id: '/_app/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AppDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/databases': {
      id: '/_app/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AppDatabasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug': {
      id: '/_app/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof AppPSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabasesRoute: typeof AppDatabasesRoute
  AppDeploymentsRoute: typeof AppDeploymentsRoute
  AppLocalRoute: typeof AppLocalRoute
  AppNewRoute: typeof AppNewRoute
  AppOauthRoute: typeof AppOauthRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTokensRoute: typeof AppTokensRoute
  AppPSlugRoute: typeof AppPSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabasesRoute: AppDatabasesRoute,
  AppDeploymentsRoute: AppDeploymentsRoute,
  AppLocalRoute: AppLocalRoute,
  AppNewRoute: AppNewRoute,
  AppOauthRoute: AppOauthRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTokensRoute: AppTokensRoute,
  AppPSlugRoute: AppPSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
